version: '3.5'

services:

  ## --------------------------------------------------
  ## | Web Server Php7.2.8-apache and required Extensions
  ## --------------------------------------------------
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:9090:${NODE_PORT}"
    restart: always
    depends_on:
      - mongodb

  ## --------------------------------------------------
  ## | Database Server (Mongo 4.0.10 )
  ## --------------------------------------------------
  mongodb:
    image: mongo:4.0.10-xenial
    ports:
      - "127.0.0.1:27019:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
